name: Tests

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  test-mssql:
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        dependency-versions: ["highest", "lowest"]
    uses: ./.github/workflows/test-mssql.yml
    secrets: inherit
    with:
      php-version: ${{ matrix.php-version }}
      dependency-versions: ${{ matrix.dependency-versions }}

  test-pgsql:
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        dependency-versions: ["highest", "lowest"]
    uses: ./.github/workflows/test-pgsql.yml
    secrets: inherit
    with:
      php-version: ${{ matrix.php-version }}
      dependency-versions: ${{ matrix.dependency-versions }}

  test-mysql:
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        dependency-versions: ["highest", "lowest"]
    uses: ./.github/workflows/test-mysql.yml
    secrets: inherit
    with:
      php-version: ${{ matrix.php-version }}
      dependency-versions: ${{ matrix.dependency-versions }}

  test-sqlite:
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        dependency-versions: ["highest", "lowest"]
        db-connection: ["sqlite_file", "sqlite_inmemory"]
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: ${{ matrix.php-version }}
      dependency-versions: ${{ matrix.dependency-versions }}
      db-connection: ${{ matrix.db-connection }}
