name: Tests

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  # PHP 8.4
  test-8_4-mssql:
    uses: ./.github/workflows/test-mssql.yml
    secrets: inherit
    with:
      php-version: '8.4'
      run-sonarqube-analysis: true

  test-8_4-pgsql:
    uses: ./.github/workflows/test-pgsql.yml
    secrets: inherit
    with:
      php-version: '8.4'

  test-8_4-mysql:
    uses: ./.github/workflows/test-mysql.yml
    secrets: inherit
    with:
      php-version: '8.4'

  test-8_4-sqlite_file:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.4'
      db-connection: 'sqlite_file'

  test-8_4-sqlite_inmemory:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.4'
      db-connection: 'sqlite_inmemory'
      
  # PHP 8.3
  test-8_3-mssql:
    uses: ./.github/workflows/test-mssql.yml
    secrets: inherit
    with:
      php-version: '8.3'

  test-8_3-pgsql:
    uses: ./.github/workflows/test-pgsql.yml
    secrets: inherit
    with:
      php-version: '8.3'

  test-8_3-mysql:
    uses: ./.github/workflows/test-mysql.yml
    secrets: inherit
    with:
      php-version: '8.3'

  test-8_3-sqlite_file:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.3'
      db-connection: 'sqlite_file'

  test-8_3-sqlite_inmemory:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.3'
      db-connection: 'sqlite_inmemory'
      
  # PHP 8.2
  test-8_2-mssql:
    uses: ./.github/workflows/test-mssql.yml
    secrets: inherit
    with:
      php-version: '8.2'

  test-8_2-pgsql:
    uses: ./.github/workflows/test-pgsql.yml
    secrets: inherit
    with:
      php-version: '8.2'

  test-8_2-mysql:
    uses: ./.github/workflows/test-mysql.yml
    secrets: inherit
    with:
      php-version: '8.2'

  test-8_2-sqlite_file:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.2'
      db-connection: 'sqlite_file'

  test-8_2-sqlite_inmemory:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.2'
      db-connection: 'sqlite_inmemory'
      
  # PHP 8.1
  test-8_1-mssql:
    uses: ./.github/workflows/test-mssql.yml
    secrets: inherit
    with:
      php-version: '8.1'

  test-8_1-pgsql:
    uses: ./.github/workflows/test-pgsql.yml
    secrets: inherit
    with:
      php-version: '8.1'

  test-8_1-mysql:
    uses: ./.github/workflows/test-mysql.yml
    secrets: inherit
    with:
      php-version: '8.1'

  test-8_1-sqlite_file:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.1'
      db-connection: 'sqlite_file'

  test-8_1-sqlite_inmemory:
    uses: ./.github/workflows/test-sqlite.yml
    secrets: inherit
    with:
      php-version: '8.1'
      db-connection: 'sqlite_inmemory'
