name: "Test PostgreSQL"

on:
  workflow_call:
    inputs:
      php-version:
        description: "The PHP version to build against"
        type: string
        required: true
      dependency-versions:
        description: "Whether to test against the highest or lowest dependency versions. Values: highest, lowest"
        type: string
        required: true

jobs:
  test_pgsql:
    name: "Test PostgreSQL on PHP ${{ inputs.php-version }}"
    runs-on: ubuntu-latest
    services:
      pgsql:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: "scoutdb"
          POSTGRES_USER: "scoutdb"
          POSTGRES_PASSWORD: "${{ secrets.TESTS_PGSQL_DB_SECRET }}"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -d scoutdb"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 20
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: pcov

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer dependencies
        uses: ramsey/composer-install@4.0.0
        with:
          dependency-versions: ${{ inputs.dependency-versions }}

      - name: Run phpunit tests
        run: composer test
        env:
          DB_CONNECTION: "pgsql"
          DB_PGSQL_DATABASE: "scoutdb"
          DB_PGSQL_USERNAME: "scoutdb"
          DB_PGSQL_PASSWORD: ${{ secrets.TESTS_PGSQL_DB_SECRET }}
